### PR TITLE
Implement thread priority into sleeping threads

### PR DESCRIPTION
**Pull request by FiniteReality**
In a project I was using copas in, I was having issues where copas would not resume a thread correctly which would lead to disconnects with the websocket API I was using, as the connection was timing out because I wasn't able to send a 'heartbeat' when I needed to.

This PR adds a mechanism for setting the priority of a thread as it yields, which in my case alleviated the problem as I could set the priority of the thread which was handling the heartbeats to a fairly high value to ensure it would always be checked in the main loop.

### CODE REVIEW

**Comment by Tieske** [comment]
Wondering, if connections timeout, then something else is blocking for too long. So maybe you have another underlying issue here?

Or am I not getting it?

**Comment by Tieske** [comment]
@FiniteReality ping any update on this?

**Comment by FiniteReality** [comment]
Oh wow, I forgot all about this PR. As for things that were blocking, I think the flow was something like this:

* Add thread to read data from a socket (I'm using copas in a client-style situation as something like libuv/libev, because I haven't gotten around to learning it yet :stuck_out_tongue:)
* Add thread to send data on same socket (The protocol over said socket requires I send a "heartbeat" every 40s or so to ensure my connection stays alive)

Since both "threads" require a constantly running while loop, to allow other code to run I need to yield control to something else, but I couldn't manage to get a socket read to yield until data was available (this is likely my problem) so I ended up hacking something into copas where I could specify "resume this one first if possible" which fixed my problem.

Of course, I haven't touched said code for a long while so I'm not entirely sure if that was the case.

**Comment by Tieske** [comment]
let's close this for now. If thread priority comes up again we can have another look.

**Pull request closed without merging**
